build-php-8.1-cli-xdebug:
  stage: build-xdebug
  only:
    refs:
      - master
    changes:
      - 8.1-cli/*
      - 8.1-cli-xdebug/*
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:8.1-cli-xdebug-$CI_COMMIT_SHORT_SHA 8.1-cli-xdebug/
    - docker push $CI_REGISTRY_IMAGE:8.1-cli-xdebug-$CI_COMMIT_SHORT_SHA

test-php-8.1-cli-xdebug:
  stage: test-xdebug
  needs: ["build-php-8.1-cli-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-cli/*
      - 8.1-cli-xdebug/*
  script:
    #- docker pull $CI_REGISTRY_IMAGE:8.1-cli-xdebug-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-8.1-cli-xdebug:
  stage: deploy-xdebug
  needs: ["test-php-8.1-cli-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-cli/*
      - 8.1-cli-xdebug/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:8.1-cli-xdebug-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:8.1-cli-xdebug-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:8.1-cli-xdebug
    - docker push $CI_REGISTRY_IMAGE:8.1-cli-xdebug

deploy-php-8.1-cli-xdebug-to-hub:
  stage: deploy-xdebug
  needs: ["test-php-8.1-cli-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-cli/*
      - 8.1-cli-xdebug/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:8.1-cli-xdebug-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:8.1-cli-xdebug-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:8.1-cli-xdebug
    - docker push $DOCKER_HUB_REPOSITORY:8.1-cli-xdebug
    - docker rmi $DOCKER_HUB_REPOSITORY:8.1-cli-xdebug

build-php-8.1-fpm-xdebug:
  stage: build-xdebug
  only:
    refs:
      - master
    changes:
      - 8.1-fpm/*
      - 8.1-fpm-xdebug/*
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:8.1-fpm-xdebug-$CI_COMMIT_SHORT_SHA 8.1-fpm-xdebug/
    - docker push $CI_REGISTRY_IMAGE:8.1-fpm-xdebug-$CI_COMMIT_SHORT_SHA

test-php-8.1-fpm-xdebug:
  stage: test-xdebug
  needs: ["build-php-8.1-fpm-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-fpm/*
      - 8.1-fpm-xdebug/*
  script:
    #- docker pull $CI_REGISTRY_IMAGE:8.1-fpm-xdebug-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-8.1-fpm-xdebug:
  stage: deploy-xdebug
  needs: ["test-php-8.1-fpm-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-fpm/*
      - 8.1-fpm-xdebug/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:8.1-fpm-xdebug-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:8.1-fpm-xdebug-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:8.1-fpm-xdebug
    - docker push $CI_REGISTRY_IMAGE:8.1-fpm-xdebug

deploy-php-8.1-fpm-xdebug-to-hub:
  stage: deploy-xdebug
  needs: ["test-php-8.1-fpm-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-fpm/*
      - 8.1-fpm-xdebug/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:8.1-fpm-xdebug-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:8.1-fpm-xdebug-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:8.1-fpm-xdebug
    - docker push $DOCKER_HUB_REPOSITORY:8.1-fpm-xdebug
    - docker rmi $DOCKER_HUB_REPOSITORY:8.1-fpm-xdebug

build-php-8.1-apache-xdebug:
  stage: build-xdebug
  only:
    refs:
      - master
    changes:
      - 8.1-apache/*
      - 8.1-apache-xdebug/*
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:8.1-apache-xdebug-$CI_COMMIT_SHORT_SHA 8.1-apache-xdebug/
    - docker push $CI_REGISTRY_IMAGE:8.1-apache-xdebug-$CI_COMMIT_SHORT_SHA

test-php-8.1-apache-xdebug:
  stage: test-xdebug
  needs: ["build-php-8.1-apache-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-apache/*
      - 8.1-apache-xdebug/*
  script:
    #- docker pull $CI_REGISTRY_IMAGE:8.1-apache-xdebug-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-8.1-apache-xdebug:
  stage: deploy-xdebug
  needs: ["test-php-8.1-apache-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-apache/*
      - 8.1-apache-xdebug/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:8.1-apache-xdebug-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:8.1-apache-xdebug-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:8.1-apache-xdebug
    - docker push $CI_REGISTRY_IMAGE:8.1-apache-xdebug

deploy-php-8.1-apache-xdebug-to-hub:
  stage: deploy-xdebug
  needs: ["test-php-8.1-apache-xdebug"]
  only:
    refs:
      - master
    changes:
      - 8.1-apache/*
      - 8.1-apache-xdebug/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:8.1-apache-xdebug-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:8.1-apache-xdebug-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:8.1-apache-xdebug
    - docker push $DOCKER_HUB_REPOSITORY:8.1-apache-xdebug
    - docker rmi $DOCKER_HUB_REPOSITORY:8.1-apache-xdebug
