build-php-7.4-cli:
  stage: build
  only:
    refs:
      - master
    changes:
      - 7.4-cli/*
  script:
    - docker build --pull -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli-$CI_COMMIT_SHORT_SHA 7.4-cli/
    - docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli-$CI_COMMIT_SHORT_SHA

test-php-7.4-cli:
  stage: test
  only:
    refs:
      - master
    changes:
      - 7.4-cli/*
  script:
    #- docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-7.4-cli:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - 7.4-cli/*
  script:
    - docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli-$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli-$CI_COMMIT_SHORT_SHA $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli
    - docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli

deploy-php-7.4-cli-to-hub:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - 7.4-cli/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli-$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-cli-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:7.4-cli
    - docker push $DOCKER_HUB_REPOSITORY:7.4-cli
    - docker rmi $DOCKER_HUB_REPOSITORY:7.4-cli

build-php-7.4-fpm:
  stage: build
  only:
    refs:
      - master
    changes:
      - 7.4-fpm/*
  script:
    - docker build --pull -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm-$CI_COMMIT_SHORT_SHA 7.4-fpm/
    - docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm-$CI_COMMIT_SHORT_SHA

test-php-7.4-fpm:
  stage: test
  only:
    refs:
      - master
    changes:
      - 7.4-fpm/*
  script:
    #- docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-7.4-fpm:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - 7.4-fpm/*
  script:
    - docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm-$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm-$CI_COMMIT_SHORT_SHA $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm
    - docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm

deploy-php-7.4-fpm-to-hub:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - 7.4-fpm/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm-$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-fpm-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:7.4-fpm
    - docker push $DOCKER_HUB_REPOSITORY:7.4-fpm
    - docker rmi $DOCKER_HUB_REPOSITORY:7.4-fpm

build-php-7.4-apache:
  stage: build
  only:
    refs:
      - master
    changes:
      - 7.4-apache/*
  script:
    - docker build --pull -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache-$CI_COMMIT_SHORT_SHA 7.4-apache/
    - docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache-$CI_COMMIT_SHORT_SHA

test-php-7.4-apache:
  stage: test
  only:
    refs:
      - master
    changes:
      - 7.4-apache/*
  script:
    #- docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-7.4-apache:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - 7.4-apache/*
  script:
    - docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache-$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache-$CI_COMMIT_SHORT_SHA $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache
    - docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache

deploy-php-7.4-apache-to-hub:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - 7.4-apache/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache-$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:7.4-apache-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:7.4-apache
    - docker push $DOCKER_HUB_REPOSITORY:7.4-apache
    - docker rmi $DOCKER_HUB_REPOSITORY:7.4-apache
