build-php-7.2-cli:
  stage: build
  only:
    refs:
      - master
    changes:
      - 7.2-cli/*
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:7.2-cli-$CI_COMMIT_SHORT_SHA 7.2-cli/
    - docker push $CI_REGISTRY_IMAGE:7.2-cli-$CI_COMMIT_SHORT_SHA

test-php-7.2-cli:
  stage: test
  needs: ["build-php-7.2-cli"]
  only:
    refs:
      - master
    changes:
      - 7.2-cli/*
  script:
    #- docker pull $CI_REGISTRY_IMAGE:7.2-cli-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-7.2-cli:
  stage: deploy
  needs: ["test-php-7.2-cli"]
  only:
    refs:
      - master
    changes:
      - 7.2-cli/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:7.2-cli-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:7.2-cli-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:7.2-cli
    - docker push $CI_REGISTRY_IMAGE:7.2-cli

deploy-php-7.2-cli-to-hub:
  stage: deploy
  needs: ["test-php-7.2-cli"]
  only:
    refs:
      - master
    changes:
      - 7.2-cli/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:7.2-cli-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:7.2-cli-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:7.2-cli
    - docker push $DOCKER_HUB_REPOSITORY:7.2-cli
    - docker rmi $DOCKER_HUB_REPOSITORY:7.2-cli

build-php-7.2-fpm:
  stage: build
  only:
    refs:
      - master
    changes:
      - 7.2-fpm/*
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:7.2-fpm-$CI_COMMIT_SHORT_SHA 7.2-fpm/
    - docker push $CI_REGISTRY_IMAGE:7.2-fpm-$CI_COMMIT_SHORT_SHA

test-php-7.2-fpm:
  stage: test
  needs: ["build-php-7.2-fpm"]
  only:
    refs:
      - master
    changes:
      - 7.2-fpm/*
  script:
    #- docker pull $CI_REGISTRY_IMAGE:7.2-fpm-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-7.2-fpm:
  stage: deploy
  needs: ["test-php-7.2-fpm"]
  only:
    refs:
      - master
    changes:
      - 7.2-fpm/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:7.2-fpm-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:7.2-fpm-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:7.2-fpm
    - docker push $CI_REGISTRY_IMAGE:7.2-fpm

deploy-php-7.2-fpm-to-hub:
  stage: deploy
  needs: ["test-php-7.2-fpm"]
  only:
    refs:
      - master
    changes:
      - 7.2-fpm/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:7.2-fpm-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:7.2-fpm-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:7.2-fpm
    - docker push $DOCKER_HUB_REPOSITORY:7.2-fpm
    - docker rmi $DOCKER_HUB_REPOSITORY:7.2-fpm

build-php-7.2-apache:
  stage: build
  only:
    refs:
      - master
    changes:
      - 7.2-apache/*
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:7.2-apache-$CI_COMMIT_SHORT_SHA 7.2-apache/
    - docker push $CI_REGISTRY_IMAGE:7.2-apache-$CI_COMMIT_SHORT_SHA

test-php-7.2-apache:
  stage: test
  needs: ["build-php-7.2-apache"]
  only:
    refs:
      - master
    changes:
      - 7.2-apache/*
  script:
    #- docker pull $CI_REGISTRY_IMAGE:7.2-apache-$CI_COMMIT_SHORT_SHA
    - exit 0

deploy-php-7.2-apache:
  stage: deploy
  needs: ["test-php-7.2-apache"]
  only:
    refs:
      - master
    changes:
      - 7.2-apache/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:7.2-apache-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:7.2-apache-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:7.2-apache
    - docker push $CI_REGISTRY_IMAGE:7.2-apache

deploy-php-7.2-apache-to-hub:
  stage: deploy
  needs: ["test-php-7.2-apache"]
  only:
    refs:
      - master
    changes:
      - 7.2-apache/*
  script:
    - echo $DOCKER_HUB_PASSWORD |docker login -u $DOCKER_HUB_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:7.2-apache-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:7.2-apache-$CI_COMMIT_SHORT_SHA $DOCKER_HUB_REPOSITORY:7.2-apache
    - docker push $DOCKER_HUB_REPOSITORY:7.2-apache
    - docker rmi $DOCKER_HUB_REPOSITORY:7.2-apache
